project:
  type: website

website:
  title: "Jarguedasvenegas.github.io"
 # navbar:
   # right:
    #  - about.qmd
     # - icon: github
      #  href: https://github.com/
      #- icon: twitter
       # href: https://twitter.com#

  navbar:
    left:
    - text: "Inicio"
      file: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css



